version: '3'

services:
  encurtador-db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db_encurtador
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
