api:
  host: localhost
  port: 3000
  prefix: api/v1

app:
  host: localhost
  port: 8080

swagger:
  title: API RESTful Encurtador
  description: API RESTful Encurtador de URL
  version: 0.0.1
  contact:
    name: Diogo Souza
    email: diogo.souza@msn.com
    repository: https://github.com/dirsouza/we-encurtador
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  prefix: api/v1/doc

db:
  type: postgres
  host: localhost
  port: 5432
  username: root
  password: root
  database: db_encurtador
  synchronize: false
  logging: true
